# /.github/workflows/build-image.yml

name: Dispatch Dashboard image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
env:
  #REGISTRY: harbor.spaasta.com
  #IMAGE_NAME: rancher/v2.11.0
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # The target repo

jobs:
  build:
    name: Build Dashboard image
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_PAT }} # The PAT referenced in prerequisites
          submodules: recursive # If the repo has multiple submodules to checkout
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # This is the repo owner
          password: ${{ secrets.GITHUB_TOKEN }} # A token generated during the workflow

      - name: Build and push Dashboard image
        uses: docker/build-push-action@v2        
        with:
          context: . # Context for docker to find the Dockerfile in the submodule
          file: ./Dockerfile.example # Dockerfile you created
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v0.19
